name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      message:
        required: true
      environment:
        type: environment
jobs:
  print-inputs:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: job summary
        run: |
          echo "### inputs" >> $GITHUB_STEP_SUMMARY
          echo "- message: ${{ inputs.message }}" >> $GITHUB_STEP_SUMMARY
      
  greet:
    needs: [print-inputs]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }}"
